AWSTemplateFormatVersion: "2010-09-09"
Resources:
  Meal:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "mealId"
          AttributeType: "S"
        - AttributeName: "type"
          AttributeType: "S"
      KeySchema:
        - "AttributeName": "mealId"
          "KeyType": "HASH"
        - "AttributeName": "type"
          "KeyType": "RANGE"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      BillingMode: PAY_PER_REQUEST
      TableName: "Meal"