AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: An AWS Lambda application that calls the Lambda API.
Parameters:
  EnvironmentName:
    Type: String
    Default: dev
Resources:
  ExerciseLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /exercise-app/logs
  GetExerciseDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ServiceLambda/build/distributions/ServiceLambda.zip
      Handler: com.kenzie.capstone.service.lambda.FindExerciseData
      Runtime: java11
      Description: Get Exercise Data for given id
      MemorySize: 512
      Timeout: 240
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
        - AmazonS3FullAccess
        - AmazonDynamoDBFullAccess
      Tracing: Active
      Events:
        UpdateResource:
          Type: Api
          Properties:
            RequestParameters:
              method.request.path.exerciseId: true
            Path: /exercise/{exerciseId}
            Method: get
  GetExerciseDataUsingGSIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ServiceLambda/build/distributions/ServiceLambda.zip
      Handler: com.kenzie.capstone.service.lambda.GetExerciseDataUsingGSI
      Runtime: java11
      Description: Get Exercise Data for given type
      MemorySize: 512
      Timeout: 240
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
        - AmazonS3FullAccess
        - AmazonDynamoDBFullAccess
      Tracing: Active
      Events:
        UpdateResource:
          Type: Api
          Properties:
            RequestParameters:
              method.request.path.value: true
            Path: /exercise/type/{value}
            Method: get
  SetExerciseDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ServiceLambda/build/distributions/ServiceLambda.zip
      Handler: com.kenzie.capstone.service.lambda.SetExerciseData
      Runtime: java11
      Description: Set Exercise Data
      MemorySize: 512
      Timeout: 240
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
        - AmazonS3FullAccess
        - AmazonDynamoDBFullAccess
      Tracing: Active
      Events:
        UpdateResource:
          Type: Api
          Properties:
            Path: /exercise/
            Method: post
  GetMealDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ServiceLambda/build/distributions/ServiceLambda.zip
      Handler: com.kenzie.capstone.service.lambda.GetMealData
      Runtime: java11
      Description: Get Meal Data for given id
      MemorySize: 512
      Timeout: 240
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
        - AmazonS3FullAccess
        - AmazonDynamoDBFullAccess
      Tracing: Active
      Events:
        UpdateResource:
          Type: Api
          Properties:
            RequestParameters:
              method.request.path.mealId: true
            Path: /meal/{mealId}
            Method: get
  GetMealDataUsingGSIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ServiceLambda/build/distributions/ServiceLambda.zip
      Handler: com.kenzie.capstone.service.lambda.GetMealDataUsingGSI
      Runtime: java11
      Description: Get Meal Data for given type
      MemorySize: 512
      Timeout: 240
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
        - AmazonS3FullAccess
        - AmazonDynamoDBFullAccess
      Tracing: Active
      Events:
        UpdateResource:
          Type: Api
          Properties:
            RequestParameters:
              method.request.path.value: true
            Path: /meal/type/{value}
            Method: get
  SetMealDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ServiceLambda/build/distributions/ServiceLambda.zip
      Handler: com.kenzie.capstone.service.lambda.SetMealData
      Runtime: java11
      Description: Set Meal Data
      MemorySize: 512
      Timeout: 240
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
        - AmazonS3FullAccess
        - AmazonDynamoDBFullAccess
      Tracing: Active
      Events:
        UpdateResource:
          Type: Api
          Properties:
            Path: /meal/
            Method: post
