AWSTemplateFormatVersion: "2010-09-09"
Resources:
  Exercises:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "exerciseId"
          AttributeType: "S"
        - AttributeName: "type"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "exerciseId"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        - IndexName: "TypeIndex"  # Name of the GSI
          KeySchema:
            - AttributeName: "type"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"  # You can change this to include specific attributes
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      BillingMode: PAY_PER_REQUEST
      TableName: "Exercises"
